# === Install Database CLI Clients ===
- name: Install MySQL, PostgreSQL, and MSSQL Clients
  apt:
    name:
      - mycli
      - postgresql-client
      - freetds-bin # Needed for SQL Server
      - sqlite3
    state: present
    update_cache: yes
